apiVersion: v1
kind: Service
metadata:
  name: bftsmart-client
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9091"
spec:
  selector:
    app: bftsmart-client
  ports:
    - port: 9091
      targetPort: 9091
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bftsmart-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bftsmart-client
  template:
    metadata:
      labels:
        app: bftsmart-client
    spec:
      # affinity:
      #   podAntiAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       - labelSelector:
      #           matchExpressions:
      #             - key: app
      #               operator: In
      #               values:
      #                 - bftsmart-server
      #         topologyKey: kubernetes.io/hostname
      containers:
        - name: bftsmart-client
          image: balajia/bftsmart:latest
          imagePullPolicy: Always
          command:
            - "/bin/bash"
            - "-ecx"
            # The use of qualified `hostname -f` is crucial:
            # Other nodes aren't able to look up the unqualified hostname.
          args: 
            - "curl ssrg:5060/config > config/hosts.config && ./smartrun.sh bftsmart.demo.microbenchmarks.ThroughputLatencyClient $RANDOM 10 10000 1024 1 0 0 default"
          env:
            - name: HOSTMACHINE
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: REGION
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
      # No pre-stop hook is required, a SIGTERM plus some time is all that's
      # needed for graceful shutdown of a node.
      terminationGracePeriodSeconds: 1
      hostAliases:
        - ip: "198.82.148.41"
          hostnames:
            - "ssrg"
